#include<iostream>
using namespace std;
class Base{
 int a; 
 const int b;//we need Initializer List
 int &c;////we need Initializer List
 int *d;
    public:
    Base(int a, const int b, int &c):a(a),b(b),c(c){//Initializer List no default constructor will be generated by compiler
        d = new int(10);
    };
    

    void display() const{
        cout<<"a: "<<a<<endl;
        cout<<"b: "<<b<<endl;
        cout<<"c: "<<c<<endl;
        cout<<"d: "<<*d<<endl;
    }
    ~Base(){
        delete d;
    }
};

class MyClass
{
    int _a;
  public :
    MyClass():_a(0){} //default constructor
    void print()
    {
        cout<<"i am class a"<<endl;
    }
}; 
//complie will give auto generated default constructor if we don't provide any constructor in class.
int main() 
{
    MyClass obj1; //-->1.it will call default constructor
    MyClass arrObj[10]; //-->2.it will call parameterized constructor
    
    arrObj[0].print();
    arrObj[1].print();


    vector<MyClass> myObj(10); //--same like above MyClass arrObj[10];
    myObj[0].print();
    myObj[1].print();
   
    vector<MyClass> myObj1; // it will call default constructor
    myObj1.emplace_back(MyClass()); //-->construct an object directly inside the vector and push_back it to the vector
    myObj1.reserve(10); //-->reserve space for 10 objects in vector
    myObj1[0].print();
    myObj1[1].print();
    myObj.push_back(MyClass());
    myObj[0].print();

   
    //Base Class Initialization in Inheritance
    int a=10,b=10,c=20;
    Base *bobj= new Base(a,b,c);
    bobj->display();
    shared_ptr<Base> bObj1 = make_shared<Base>(a,b,c);
    bobj->display();

    delete bobj;
    return 0;
}
/***************************LEARNING */
/* list of question this code will be answer
1. when we need default const?
Ans: 
    a. When you want to create an object without arguments. 
      like.
    b.When an array of objects is required. 
    c. When using STL containers in situations requiring default construction
    d. When an object is created first and initialized later.
    e. If we  define another constructor, default constructor may disappear. 


Imp push_back() vs emplace_back()
    push_back() will create a temporary object and then copy/move it into the vector.
    emplace_back() will construct the object directly in place inside the vector.
*/